# -*- coding: utf-8 -*-
"""P4_Find_If_A_File_Exists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a6NxIWKDa_dhI3ZbMRHR0DX5lh8WpwWF
"""

# This script illustrates how to find if a file exists on the system with the specified name

import os

# Path IN which we have to search file
PATH = '/home/shrinivas/Documents/GITs/Python-Programs/Scripts'   # Give your path here

def searchFile(fileName):
    ''' This function searches for the specified file name in the given PATH '''
    for root, dirs, files in os.walk(PATH):
        print('Looking in:',root)
        for Files in files:
            try:
                found = Files.find(fileName)        # Returns -1 if NOT found else returns index
                # print(found)
                if found != -1:
                    print(fileName, 'Found')
                    break
            except:
                exit()

if __name__ == '__main__':
    searchFile('6-Folder.txt')

    # OUTPUT:
    # omkarpathak@shrinivas-Inspiron-3542:~/Documents/GITs/Python-Programs/Scripts$ python P04_FindIfAFileExists.py
    # Looking in: /home/shrinivas/Documents/GITs/Python-Programs/Scripts
    # Looking in: /home/shrinivas/Documents/GITs/Python-Programs/Scripts/Tests
    # 6-Folder.txt Found